export const EXCHANGE_HELPER_TYPES = {
  SET_EXCHANGE_DATA: "SET_EXCHANGE_DATA",
  SET_EXCHANGE_ARR: "SET_EXCHANGE_ARR",
  SET_EXCHANGE_OPTION: "SET_EXCHANGE_OPTION",
  RESET_EXCHANGE: "RESET_EXCHANGE",
};
