export const EXCHANGE_TYPES = {
  SET_EXCHANGE_DATA: "SET_EXCHANGE_DATA",
  SET_EXCHANGE_ARR: "SET_EXCHANGE_ARR",
  SET_EXCHANGE_OPTION: "SET_EXCHANGE_OPTION",
  RESET_EXCHANGE: "RESET_EXCHANGE",
  REQUEST_EXCHANGE_START: "REQUEST_EXCHANGE_START",
  REQUEST_EXCHANGE_SUCCESS: "REQUEST_EXCHANGE_SUCCESS",
  REQUEST_EXCHANGE_FAILED: "REQUEST_EXCHANGE_FAILED",
  RESET_SHOW_MSG: "RESET_SHOW_MSG",
};
