export const REGISTER_HELPER_TYPES = {
  SET_STEP: "SET_STEP",
  INIT_PLAN: "INIT_PLAN",
  SHOW_PLANS: "SHOW_PLANS",
  SET_TYPE_OF_PLAN: "SET_TYPE_OF_PLAN",
  SET_TYPE_OF_PLAN_ADD: "SET_TYPE_OF_PLAN_ADD",
  SET_TYPE_OF_PLAN_REMOVE: "SET_TYPE_OF_PLAN_REMOVE",
};
