export const REGISTER_HELPER_TYPES = {
  SET_STEP: "SET_STEP",
  SET_PLAN_DATA: "SET_PLAN_DATA",
  SET_USER_DATA: "SET_USER_DATA",
  SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
  SET_REQUEST_FAILED: "SET_REQUEST_FAILED",
};
