export const SAVINGS_HELPER_TYPES = {
  SET_SAVINGS_ACTION: "SET_SAVINGS_ACTION",
  SET_SAVINGS_FORM: "SET_SAVINGS_FORM",
  SET_SAVINGS_ARR: "SET_SAVINGS_ARR",
  SET_SAVINGS_ID: "SET_SAVINGS_ID",
  SET_SAVINGS_DATA: "SET_SAVINGS_DATA",
  RESET_SAVING: "RESET_SAVING",
  SET_MODAL_SAVING: "SET_MODAL_SAVING",
};
