export const CHANGE_PASSWORD_TYPES = {
  SET_PASSWORD: "SET_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",
  REQUEST_PASSWORD_START: "REQUEST_PASSWORD_START",
  REQUEST_PASSWORD_SUCCESS: "REQUEST_PASSWORD_SUCCESS",
  REQUEST_PASSWORD_FAILED: "REQUEST_PASSWORD_FAILED",
  RESET_SHOW_MSG: "RESET_SHOW_MSG",
  SET_AUTH: "SET_AUTH",
};
