export const REGISTER_HELPER_TYPES = {
  SET_STEP: "SET_STEP",
  SET_PLAN_DATA: "SET_PLAN_DATA",
  SET_USER_DATA: "SET_USER_DATA",
  POST_REGISTER_START: "POST_REGISTER_START",
  POST_REGISTER_SUCCESS: "POST_REGISTER_SUCCESS",
  POST_REGISTER_FAILED: "POST_REGISTER_FAILED",
  GENERATE_EMAIL_CODE: "GENERATE_EMAIL_CODE",
};
