export const DASHBOARD_TYPES = {
  SET_RED_DOT: "SET_RED_DOT",
  SET_NOTIFICATION_OPEN: "SET_NOTIFICATION_OPEN",
  RESET_DASHBOARD: "RESET_DASHBOARD",
  SET_TRANSFER_NOTIFICATION_ARR: "SET_TRANSFER_NOTIFICATION_ARR",
  SET_DARK_MODE: "SET_DARK_MODE",
};
