export const REGISTER_ACTION_TYPES = {
  SET_REGISTER_USER: "SET_REGISTER_USER",
  SET_REGISTER_PLAN_ADD: "SET_REGISTER_PLAN_ADD",
  SET_REGISTER_ESENTIALS: "SET_REGISTER_ESENTIALS",
  // SET_REGISTER_PLAN_REMOVE: "SET_REGISTER_PLAN_REMOVE",
};
