export const TRANSFER_TYPES = {
  SET_ADD_TRANSFER: "SET_ADD_TRANSFER",
  SET_TRANSFER_FORM: "SET_TRANSFER_FORM",
  SET_TRANSFER_ARR: "SET_TRANSFER_ARR",
  SET_DETAIL_TRANSFER: "SET_DETAIL_TRANSFER",
  SET_TRANSFER_OPTION: "SET_TRANSFER_OPTION",
  RESET_TRANSFER: "RESET_TRANSFER",
  REQUEST_TRANSFER_START: "REQUEST_TRANSFER_START",
  REQUEST_TRANSFER_SUCCESS: "REQUEST_TRANSFER_SUCCESS",
  REQUEST_TRANSFER_FAILED: "REQUEST_TRANSFER_FAILED",
  RESET_SHOW_MSG: "RESET_SHOW_MSG",
};
