export const LOANS_DATA_TYPES = {
  SET_LOANS: "SET_LOANS",
  SET_LOANS_ARR: "SET_LOANS_ARR",
  SET_LOANS_ARR_HISTORY: "SET_LOANS_ARR_HISTORY",
  SET_LOANS_CHECK_DATA: "SET_LOANS_CHECK_DATA",
  RESET_LOANS: "RESET_LOANS",
};
