export const LOANS_DATA_TYPES = {
  SET_LOANS: "SET_LOANS",
  SET_LOANS_ARR: "SET_LOANS_ARR",
  SET_LOANS_ARR_HISTORY: "SET_LOANS_ARR_HISTORY",
  SET_LOANS_CHECK_DATA: "SET_LOANS_CHECK_DATA",
  RESET_LOANS: "RESET_LOANS",
  SET_LOAN_STATUS: "SET_LOAN_STATUS",
  REQUEST_LOANS_START: "REQUEST_LOANS_START",
  REQUEST_LOANS_SUCCESS: "REQUEST_LOANS_SUCCESS",
  REQUEST_LOANS_FAILED: "REQUEST_LOANS_FAILED",
  RESET_SHOW_MSG: "RESET_SHOW_MSG",
  RESET_LOANS_FORM: "RESET_LOANS_FORM",
};
