export const SETTINGS_TYPES = {
  SET_SETTINGS: "SET_SETTINGS",
  SET_AUTH: "SET_AUTH",
  REQUEST_SETTINGS_START: "REQUEST_SETTINGS_START",
  REQUEST_SETTINGS_SUCCESS: "REQUEST_SETTINGS_SUCCESS",
  REQUEST_SETTINGS_FAILED: "REQUEST_SETTINGS_FAILED",
  RESET_SHOW_MSG: "RESET_SHOW_MSG",
};
