export const SETTINGS_TYPES = {
  SET_SETTINGS: "SET_SETTINGS",
  REQUEST_SETTINGS_START: "REQUEST_SETTINGS_START",
  REQUEST_SETTINGS_SUCCESS: "REQUEST_SETTINGS_SUCCESS",
  REQUEST_SETTINGS_FAILED: "REQUEST_SETTINGS_FAILED",
  RESET_SETTINGS: "RESET_SETTINGS",
};
