export const TRANSFER_HELPER_TYPES = {
  SET_ADD_TRANSFER: "SET_ADD_TRANSFER",
  SET_TRANSFER_FORM: "SET_TRANSFER_FORM",
  SET_TRANSFER_ARR: "SET_TRANSFER_ARR",
  SET_DETAIL_TRANSFER: "SET_DETAIL_TRANSFER",
};
