export const REGISTER_TYPES = {
  SET_STEP: "SET_STEP",
  SET_PLAN_DATA: "SET_PLAN_DATA",
  SET_USER_DATA: "SET_USER_DATA",
  POST_REGISTER_START: "POST_REGISTER_START",
  POST_REGISTER_SUCCESS: "POST_REGISTER_SUCCESS",
  POST_REGISTER_FAILED: "POST_REGISTER_FAILED",
  GENERATE_EMAIL_CODE: "GENERATE_EMAIL_CODE",
  RESET_SIGNUP: "RESET_SIGNUP",
  SET_TOKEN: "SET_TOKEN",
  SET_REGISTER_USER: "SET_REGISTER_USER",
  SET_REGISTER_PLAN_ADD: "SET_REGISTER_PLAN_ADD",
  SET_REGISTER_ADITIONALS: "SET_REGISTER_ADITIONALS",
};
