export const CARD_TYPES = {
  SET_CARD: "SET_CARD",
  SET_CARD_EDIT_ERROR: "SET_CARD_EDIT_ERROR",
  SET_CARD_CURRENT: "SET_CARD_CURRENT",
  SET_CARD_CURRENT_EDIT: "SET_CARD_CURRENT_EDIT",
  SET_CARD_ARR: "SET_CARD_ARR",
  SET_CARD_NEW: "SET_CARD_NEW",
};
