export const DEPOSITS_HELPER_TYPES = {
  SET_DEPOSIT_ACTION: "SET_DEPOSIT_ACTION",
  SET_DEPOSIT_FORM: "SET_DEPOSIT_FORM",
  SET_DEPOSIT_ARR: "SET_DEPOSIT_ARR",
  SET_DEPOSIT_DATA: "SET_DEPOSIT_DATA",
  SET_DEPOSIT_OPTION: "SET_DEPOSIT_OPTION",
  RESET_DEPOSIT: "RESET_DEPOSIT",
  REQUEST_DEPOSIT_START: "REQUEST_DEPOSIT_START",
  REQUEST_DEPOSIT_SUCCESS: "REQUEST_DEPOSIT_SUCCESS",
  REQUEST_DEPOSIT_FAILED: "REQUEST_DEPOSIT_FAILED",
  RESET_SHOW_MSG: "RESET_SHOW_MSG",
};
