export const REGISTER_ACTION_TYPES = {
  SET_REGISTER_USER: "SET_REGISTER_USER",
  SET_REGISTER_PLAN_ADD: "SET_REGISTER_PLAN_ADD",
  SET_REGISTER_ADITIONALS: "SET_REGISTER_ADITIONALS",
  POST_REGISTER_START: "POST_REGISTER_START",
  POST_REGISTER_SUCCESS: "POST_REGISTER_SUCCESS",
  POST_REGISTER_FAILED: "POST_REGISTER_FAILED",
};
