export const DEPOSITS_HELPER_TYPES = {
  SET_DEPOSIT_ACTION: "SET_DEPOSIT_ACTION",
  SET_DEPOSIT_FORM: "SET_DEPOSIT_FORM",
  SET_DEPOSIT_ARR: "SET_DEPOSIT_ARR",
  SET_DEPOSIT_DATA: "SET_DEPOSIT_DATA",
  SET_DEPOSIT_FILTER: "SET_DEPOSIT_FILTER",
};
